import daisyui from 'daisyui';

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {},
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        neomist_vapor: {
          primary: '#6f6cf6',
          'primary-content': '#ffffff',
          secondary: '#9d86f7',
          'secondary-content': '#ffffff',
          accent: '#53c7e8',
          'accent-content': '#103746',
          neutral: '#66708f',
          'neutral-content': '#ffffff',
          info: '#5f8dff',
          'info-content': '#ffffff',
          success: '#3bc8aa',
          'success-content': '#ffffff',
          warning: '#f2a65a',
          'warning-content': '#4b2e14',
          error: '#ef6b8f',
          'error-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f7f8fc',
          'base-300': '#e7e9f3',
          'base-content': '#27304a',
          '--rounded-box': '1.4rem',
          '--rounded-btn': '1rem',
          '--rounded-badge': '999px',
          '--animation-btn': '0.2s',
          '--border-btn': '1px',
          '--btn-text-case': 'none',
          '--tab-border': '1px',
          '--tab-radius': '0.9rem',
        },
      },
      {
        neomist_vapor_dark: {
          primary: '#8f8cff',
          'primary-content': '#14182c',
          secondary: '#be9cff',
          'secondary-content': '#14182c',
          accent: '#67d8f4',
          'accent-content': '#102b36',
          neutral: '#b4bdd8',
          'neutral-content': '#14182c',
          info: '#88a7ff',
          'info-content': '#101a38',
          success: '#58d2b6',
          'success-content': '#0f2a24',
          warning: '#f3b474',
          'warning-content': '#3d2712',
          error: '#ff819f',
          'error-content': '#351120',
          'base-100': '#161b2e',
          'base-200': '#1d243b',
          'base-300': '#313a57',
          'base-content': '#eef2ff',
          '--rounded-box': '1.4rem',
          '--rounded-btn': '1rem',
          '--rounded-badge': '999px',
          '--animation-btn': '0.2s',
          '--border-btn': '1px',
          '--btn-text-case': 'none',
          '--tab-border': '1px',
          '--tab-radius': '0.9rem',
        },
      },
    ],
  },
};
